# Constants

NO_DRIVERS_AVAILABLE = "NO_DRIVERS_AVAILABLE"
RIDE_START = "RIDE_STARTED"
RIDE_STOP = "RIDE_STOPPED"
INVALID_RIDE = "INVALID_RIDE"
RIDE_NOT_COMPLETED = "RIDE_NOT_COMPLETED"
DRIVERS_MATCHED = "DRIVERS_MATCHED"

CHARGE_SHEET = {
    "BASE": 50,
    "DISTANCE_CHARGE": 6.5,
    "TIME_TAKEN": 2,
    "SERVICE_TAX": 0.20
}
